name: Deploy to Public HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to public_html
      run: |
        cp -r  /public_html/abogar/
